
import { Transaksi } from "../../types";

// Initial sample data
export const initialTransaksi: Transaksi[] = [
  // Simpanan
  { 
    id: "TR0001", 
    tanggal: "2025-04-20",
    anggotaId: "AG0001",
    anggotaNama: "Budi Santoso",
    jenis: "Simpan",
    jumlah: 500000,
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  { 
    id: "TR0004", 
    tanggal: "2025-04-15",
    anggotaId: "AG0002",
    anggotaNama: "Dewi Lestari",
    jenis: "Simpan",
    jumlah: 750000,
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0006",
    tanggal: "2025-04-10",
    anggotaId: "AG0001",
    anggotaNama: "Budi Santoso",
    jenis: "Simpan",
    jumlah: 300000,
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0007",
    tanggal: "2025-04-05",
    anggotaId: "AG0003",
    anggotaNama: "Ahmad Hidayat",
    jenis: "Simpan",
    jumlah: 450000,
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Pinjaman
  { 
    id: "TR0002", 
    tanggal: "2025-04-18",
    anggotaId: "AG0004",
    anggotaNama: "Sri Wahyuni",
    jenis: "Pinjam",
    jumlah: 2000000,
    keterangan: "Pinjaman untuk modal usaha",
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  { 
    id: "TR0005", 
    tanggal: "2025-04-12",
    anggotaId: "AG0005",
    anggotaNama: "Agus Setiawan",
    jenis: "Pinjam",
    jumlah: 5000000,
    keterangan: "Pinjaman untuk renovasi rumah",
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0008",
    tanggal: "2025-03-25",
    anggotaId: "AG0001",
    anggotaNama: "Budi Santoso",
    jenis: "Pinjam",
    jumlah: 4000000,
    keterangan: "Pinjaman untuk biaya pendidikan",
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0009",
    tanggal: "2025-02-15",
    anggotaId: "AG0002",
    anggotaNama: "Dewi Lestari",
    jenis: "Pinjam",
    jumlah: 3500000,
    keterangan: "Pinjaman untuk kesehatan",
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Angsuran
  { 
    id: "TR0003", 
    tanggal: "2025-04-17",
    anggotaId: "AG0003",
    anggotaNama: "Ahmad Hidayat",
    jenis: "Angsuran",
    jumlah: 250000,
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0010",
    tanggal: "2025-04-02",
    anggotaId: "AG0001",
    anggotaNama: "Budi Santoso",
    jenis: "Angsuran",
    jumlah: 350000,
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0011",
    tanggal: "2025-03-30",
    anggotaId: "AG0004",
    anggotaNama: "Sri Wahyuni",
    jenis: "Angsuran",
    jumlah: 200000,
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0012",
    tanggal: "2025-03-15",
    anggotaId: "AG0002",
    anggotaNama: "Dewi Lestari",
    jenis: "Angsuran",
    jumlah: 300000,
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Pinjaman yang akan jatuh tempo
  {
    id: "TR0013",
    tanggal: "2025-04-10",
    anggotaId: "AG0003",
    anggotaNama: "Ahmad Hidayat",
    jenis: "Pinjam",
    jumlah: 2500000,
    keterangan: "Pinjaman untuk keperluan usaha",
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0014",
    tanggal: "2025-04-20",
    anggotaId: "AG0001",
    anggotaNama: "Budi Santoso",
    jenis: "Pinjam",
    jumlah: 1500000,
    keterangan: "Pinjaman untuk pernikahan anak",
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  
  // Pinjaman yang sudah lewat jatuh tempo
  {
    id: "TR0015",
    tanggal: "2024-03-15",
    anggotaId: "AG0004",
    anggotaNama: "Sri Wahyuni",
    jenis: "Pinjam",
    jumlah: 3000000,
    keterangan: "Pinjaman untuk modal usaha",
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0016",
    tanggal: "2024-02-25",
    anggotaId: "AG0002",
    anggotaNama: "Dewi Lestari",
    jenis: "Pinjam",
    jumlah: 2800000,
    keterangan: "Pinjaman untuk renovasi rumah",
    status: "Sukses",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  
  // Pengajuan
  {
    id: "TR0017",
    tanggal: "2025-04-18",
    anggotaId: "AG0001",
    anggotaNama: "Budi Santoso",
    jenis: "Pinjam",
    jumlah: 5000000,
    keterangan: "Pengajuan pinjaman untuk modal usaha",
    status: "Pending",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0018",
    tanggal: "2025-04-16",
    anggotaId: "AG0002",
    anggotaNama: "Dewi Lestari",
    jenis: "Simpan",
    jumlah: 1000000,
    keterangan: "Pengajuan simpanan sukarela",
    status: "Pending",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0019",
    tanggal: "2025-04-15",
    anggotaId: "AG0003",
    anggotaNama: "Ahmad Hidayat",
    jenis: "Pinjam",
    jumlah: 3000000,
    keterangan: "Pengajuan pinjaman untuk pendidikan",
    status: "Pending",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "TR0020",
    tanggal: "2025-04-14",
    anggotaId: "AG0004",
    anggotaNama: "Sri Wahyuni",
    jenis: "Simpan",
    jumlah: 800000,
    keterangan: "Pengajuan simpanan wajib",
    status: "Pending",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
