// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvigmyzmcfjfxikasvuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12aWdteXptY2ZqZnhpa2FzdnVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODEyMjMsImV4cCI6MjA2Mjc1NzIyM30.tK7OzvOU1054GABJDub0s4nKId1rxdGdWXFxkwugbKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);